### ISSUE TITLE
gradle-wrapper.jar missing

### ISSUE THREAD

**Issue by yadavjpr** [dnebing/filesystem-access#1]
gradle-wrapper.jar is missing in /gradle/wrapper/ folder, it cause following error:

> kailash.chand.yadav@yadavjpr /c/LR/filesystem-access/modules/apps/filesystem-access-api (master)
> $ ../../../gradlew build
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by dnebing** [comment]
Unfortunate casualty of aggressive .gitignore.  Jar added to repository, thanks!
